services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    healthcheck:
      test: ['CMD', 'echo', 'ruok', '|', 'nc', 'localhost', '2181']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - '9092:9092'
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ['CMD', 'kafka-broker-api-versions', '--bootstrap-server', 'kafka:9092']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/event_api
      - KAFKA_BROKERS=kafka:9092
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - JWT_SECRET=${JWT_SECRET:-secret}
    ports:
      - '3000:3000'
    command: >
      sh -c "if [ \"$NODE_ENV\" = \"development\" ]; then npm run docker:launch:dev; else npm run start; fi"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  data_generator:
    build:
      context: ./data_generator
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKERS=kafka:9092
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}  # Optional if generating fake data
      - GENERATOR_INTERVAL_MIN=500  # Min delay between events (ms)
      - GENERATOR_INTERVAL_MAX=2000 # Max delay between events (ms)
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    
volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
